QUESTION_BANK = {
    "u6_7": {
        "title": "Under 6 & 7",
        "summary": "No goalkeeper, no throw-ins, no corner kicks — and the simplest restarts in MiniRoos.",
        "questions": [
            {
                "prompt": "In Under 6 & 7, how many players are on each team?",
                "choices": [
                    "4-a-side with no goalkeeper",
                    "5-a-side with a goalkeeper",
                    "7-a-side with no goalkeeper",
                    "9-a-side with a goalkeeper",
                ],
                "answer": 0,
                "explanation": "Under 6 & 7 is played 4-a-side with no goalkeeper.",
                "confidence_tip": "Start with the age-group format — player count tells you a lot about what other rules apply.",
            },
            {
                "prompt": "The ball crosses the touch line in Under 6 & 7. What is the restart?",
                "choices": [
                    "Throw-in",
                    "Kick-in or dribble-in from the touch line by the opposing team",
                    "Drop ball at the nearest mark",
                    "Indirect free kick to the defending team",
                ],
                "answer": 1,
                "explanation": "There is no throw-in at Under 6 & 7. A player from the opposing team places the ball on the touch line and passes or dribbles it into play. Opponents must be at least 5 metres away.",
                "confidence_tip": "At U6-7, lean toward simple restarts that keep the game moving — the throw-in doesn't appear until U8-9.",
            },
            {
                "prompt": "In Under 6 & 7, the ball crosses the goal line. Who restarts, and how?",
                "choices": [
                    "The attacking team takes a corner kick from the nearest arc",
                    "The goalkeeper takes a goal kick from the penalty area",
                    "The team whose goal line was crossed restarts from anywhere along that goal line, regardless of who touched the ball last",
                    "The Game Leader drops the ball at the nearest post",
                ],
                "answer": 2,
                "explanation": "There is no corner kick in Under 6 & 7. Regardless of who touched the ball last, the team whose goal line was crossed restarts from anywhere along that goal line.",
                "confidence_tip": "At U6-7 the defending team always restarts from the goal line — corner kicks don't exist yet.",
            },
            {
                "prompt": "How far must opponents retreat for a goal-line restart in Under 6 & 7?",
                "choices": [
                    "5 metres from the ball",
                    "3 metres from the ball",
                    "To the halfway line",
                    "10 metres outside the penalty area",
                ],
                "answer": 2,
                "explanation": "For goal-line restarts in Under 6 & 7, opponents must retreat to the halfway line and may move once the ball is in play.",
                "confidence_tip": "Use field landmarks — 'halfway line' is a clearer instruction than estimating metres under match pressure.",
            },
            {
                "prompt": "Can a goal be scored directly from a touch-line or goal-line restart in Under 6 & 7?",
                "choices": [
                    "Yes, always",
                    "Only from a goal-line restart",
                    "No — the ball must touch a teammate first in both cases",
                    "Only if the Game Leader signals advantage",
                ],
                "answer": 2,
                "explanation": "From both touch-line and goal-line restarts in Under 6 & 7, the ball must touch a teammate before a goal can be scored.",
                "confidence_tip": "Simplified restarts at U6-7 always require a teammate touch before a goal counts.",
            },
            {
                "prompt": "Is there an offside rule in Under 6 & 7 or Under 8 & 9?",
                "choices": [
                    "Yes, standard FIFA offside applies in both",
                    "No offside in either age group",
                    "Offside applies in U8-9 but not U6-7",
                    "Offside applies only in the attacking half in both groups",
                ],
                "answer": 1,
                "explanation": "There is no offside rule in either Under 6 & 7 or Under 8 & 9. Game Leaders should still strongly discourage permanent goal-hanging.",
                "confidence_tip": "No offside doesn't mean do nothing — discouraging goal-hanging is still part of good game leadership.",
            },
            {
                "prompt": "How is play restarted after a goal in all MiniRoos age groups?",
                "choices": [
                    "The scoring team kicks off from anywhere in their half",
                    "A pass to a teammate from the middle of the halfway line, with all players in their own half and opponents at least 5 metres away",
                    "The conceding team kicks off from the penalty area",
                    "Drop ball at the centre circle",
                ],
                "answer": 1,
                "explanation": "Across all MiniRoos age groups, play restarts with a pass to a teammate from the middle of the halfway line. All players must be in their own half, opponents at least 5 metres away, and the ball must touch a teammate before a goal can be scored.",
                "confidence_tip": "The kickoff restart is the same across all age groups — a reliable anchor in your mental rulebook.",
            },
        ],
    },
    "u8_9": {
        "title": "Under 8 & 9",
        "summary": "Throw-ins, corner kicks, a goalkeeper, and penalty decisions enter the game.",
        "questions": [
            {
                "prompt": "How many players are on each team in Under 8 & 9?",
                "choices": [
                    "4-a-side with no goalkeeper",
                    "5-a-side with a goalkeeper",
                    "7-a-side including a goalkeeper",
                    "9-a-side including a goalkeeper",
                ],
                "answer": 2,
                "explanation": "Under 8 & 9 is played 7-a-side including a goalkeeper.",
                "confidence_tip": "Knowing the format — player count and whether there's a goalkeeper — anchors your understanding of all the other rules.",
            },
            {
                "prompt": "The ball crosses the touch line in Under 8 & 9. What is the restart?",
                "choices": [
                    "Kick-in from the touch line",
                    "Drop ball at the nearest point",
                    "Throw-in",
                    "Indirect free kick",
                ],
                "answer": 2,
                "explanation": "Under 8 & 9 uses a standard throw-in. The player must use both hands, deliver from behind and over the head, and have part of each foot on or behind the touch line.",
                "confidence_tip": "Moving to U8-9 means more standard football restarts — the throw-in is the first big one to introduce.",
            },
            {
                "prompt": "Can a goal be scored directly from a throw-in in Under 8 & 9?",
                "choices": [
                    "Yes",
                    "Only if it bounces first",
                    "Only if the Game Leader allows advantage",
                    "No",
                ],
                "answer": 3,
                "explanation": "A goal cannot be scored directly from a throw-in in Under 8 & 9. Another player must touch the ball first.",
                "confidence_tip": "Throw-ins are always indirect — another player must touch the ball before a goal can count.",
            },
            {
                "prompt": "In Under 8 & 9, how must the goalkeeper restart play after gathering the ball with their hands?",
                "choices": [
                    "Kick or drop-kick directly from the hands",
                    "Throw, roll, or play from the ground with their feet — within 6 seconds",
                    "Bounce the ball and kick",
                    "Roll it to the edge of the penalty area only",
                ],
                "answer": 1,
                "explanation": "The goalkeeper may throw or roll the ball from their hands, or place it on the ground and play with their feet, within 6 seconds. They cannot kick or drop-kick directly from their hands.",
                "confidence_tip": "Lock this in: throw, roll, or ground — no kicking from the hands. Knowing this gives you a fast decision anchor.",
            },
            {
                "prompt": "In Under 8 & 9, when is the ball in play after a goal kick from within the penalty area?",
                "choices": [
                    "As soon as the keeper kicks it",
                    "When it crosses the halfway line",
                    "Once it has been kicked directly out of the penalty area",
                    "When any opponent touches it",
                ],
                "answer": 2,
                "explanation": "In Under 8 & 9, the ball is in play once it has been kicked directly out of the penalty area. Opponents must remain at least 10 metres outside until then.",
                "confidence_tip": "Watch the penalty area line — don't call it in play until the ball has clearly exited.",
            },
            {
                "prompt": "The defending team last touches the ball before it crosses the goal line in Under 8 & 9. What is the restart?",
                "choices": [
                    "Goal kick",
                    "Drop ball at the corner arc",
                    "Corner kick — the attacking team places the ball inside the nearest corner arc",
                    "Indirect free kick from the goal area",
                ],
                "answer": 2,
                "explanation": "When the defending team last touches the ball, a corner kick is awarded. The attacking team places the ball inside the nearest corner arc. A goal may be scored directly from a corner kick.",
                "confidence_tip": "Corner kicks allow direct goals — unlike throw-ins. Keep that distinction sharp.",
            },
            {
                "prompt": "What is awarded for a deliberate or serious foul inside the penalty area in Under 8 & 9?",
                "choices": [
                    "Indirect free kick from the penalty spot",
                    "Penalty kick from an 8 metre mark, with only the goalkeeper in position",
                    "Direct free kick from the edge of the penalty area",
                    "Drop ball at the six-yard box",
                ],
                "answer": 1,
                "explanation": "A penalty kick is awarded from an 8 metre penalty mark, with only the goalkeeper in position. All other players must be outside the penalty area and at least 5 metres behind the penalty mark.",
                "confidence_tip": "On penalties: mark, keeper stays, everyone else outside and 5m behind. That procedure makes the call clean and confident.",
            },
            {
                "prompt": "What type of free kick is awarded for handball or fouls and misconduct across all MiniRoos age groups?",
                "choices": [
                    "Direct free kick",
                    "Indirect free kick, with opponents at least 5 metres away",
                    "Penalty kick every time",
                    "Throw-in to the other team",
                ],
                "answer": 1,
                "explanation": "Indirect free kicks are awarded for all acts of handball or fouls and misconduct across all MiniRoos age groups. Opponents must be at least 5 metres away. A penalty kick only applies for deliberate or serious acts inside the penalty area.",
                "confidence_tip": "MiniRoos always uses indirect free kicks for fouls — not direct. Don't carry over the full Laws of the Game here.",
            },
        ],
    },
    "u10_11": {
        "title": "Under 10 & 11",
        "summary": "The largest MiniRoos format — manage the offside teaching approach and spot the small rule differences from U8-9.",
        "questions": [
            {
                "prompt": "How many players are on each team in Under 10 & 11?",
                "choices": [
                    "7-a-side including a goalkeeper",
                    "8-a-side with no goalkeeper",
                    "9-a-side including a goalkeeper",
                    "11-a-side",
                ],
                "answer": 2,
                "explanation": "Under 10 & 11 is played 9-a-side including a goalkeeper.",
                "confidence_tip": "Age-group identity matters — once you know the format, restart expectations fall into place.",
            },
            {
                "prompt": "What is different about when the ball is in play from a goalkeeper restart in Under 10 & 11 compared to Under 8 & 9?",
                "choices": [
                    "There is no difference — the rules are identical",
                    "In U10-11, the ball is also in play when the goalkeeper places it on the ground, not only when it exits the penalty area",
                    "In U10-11 the goalkeeper can kick directly from the hands",
                    "In U10-11 the ball is in play only after it crosses the halfway line",
                ],
                "answer": 1,
                "explanation": "In Under 10 & 11, the ball is in play once it moves out of the penalty area OR when the goalkeeper places it on the ground — a small but important difference from Under 8 & 9.",
                "confidence_tip": "Small wording differences between age groups matter. At U10-11, placing the ball on the ground is enough to bring it into play.",
            },
            {
                "prompt": "Is there an offside rule in Under 10 & 11?",
                "choices": [
                    "Yes, full FIFA Law 11 applies",
                    "No, but Game Leaders should direct players away from blatant goal-hanging",
                    "Yes, but only in the attacking half",
                    "Yes, but only on set pieces",
                ],
                "answer": 1,
                "explanation": "The official offside rule does not apply in Under 10 & 11. Goals can be scored from an offside position. Game Leaders should still direct players standing in blatant offside positions to move.",
                "confidence_tip": "U10-11 is a teaching age group — the offside rule is off, but your communication still shapes good habits.",
            },
            {
                "prompt": "The defending team last touches the ball before it crosses the goal line in Under 10 & 11. What is the restart?",
                "choices": [
                    "Goal kick",
                    "Drop ball at the corner arc",
                    "Corner kick — the attacking team places the ball inside the nearest corner arc",
                    "Indirect free kick from the goal area",
                ],
                "answer": 2,
                "explanation": "When the defending team last touches the ball, a corner kick is awarded. The attacking team places the ball inside the nearest corner arc. A goal may be scored directly from a corner kick.",
                "confidence_tip": "Track who touched it last — that single fact determines corner kick vs goal kick.",
            },
            {
                "prompt": "When can substitutions be made in MiniRoos?",
                "choices": [
                    "Only when the ball is out of play",
                    "Only at half-time",
                    "At any time during the game, even while the ball is in play",
                    "Only after a goal is scored",
                ],
                "answer": 2,
                "explanation": "Players may be rotated on and off the field at any time during the game. The player must be off the field before the substitute goes on. Equal playing time is a priority across all MiniRoos age groups.",
                "confidence_tip": "Rolling substitutions keep kids involved. Equal play time is the goal — keep that in mind when managing rotations.",
            },
            {
                "prompt": "An indirect free kick is awarded in MiniRoos. What does 'indirect' mean?",
                "choices": [
                    "The ball must be kicked backwards first",
                    "A goal can only be scored if the ball subsequently touches another player before entering the goal",
                    "The kicker may not touch the ball again until it is cleared",
                    "The kick must be taken from outside the penalty area",
                ],
                "answer": 1,
                "explanation": "An indirect free kick means a goal can only be scored if the ball touches another player after the kick, before entering the goal.",
                "confidence_tip": "If you award an indirect free kick, remind yourself: another touch is needed before a goal counts.",
            },
        ],
    },
}
